apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cluster
  source:
    repoURL: https://github.com/jguillemat/openshift-cluster-gitops.git
    targetRevision: main
    path: cluster-gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
