apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-demo
  namespace: cluster-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: applications
  source:
    repoURL: https://github.com/jguillemat/openshift-cluster-gitops.git
    targetRevision: main
    path: pacman
  destination:
    server: https://kubernetes.default.svc
    namespace: pacman-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
